name: CI devops 2024

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: gym-rats-nest
        run: npm install

      - name: Run tests
        working-directory: gym-rats-nest
        run: npm run test

#      - name: Build with Maven cloud
#        run:  mvn -B verify sonar:sonar -Dsonar.projectKey=$PROJECT -Dsonar.organization=$ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=SONARCLOUD_TOKEN
#        env:
#          GIT_HUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
#          ORGANIZATION: ${{ secrets.SONAR_ORGANISATION }}
#          PROJECT: ${{ secrets.SONAR_PROJECT_TOKEN }}